sudo: required
services:
  - docker

before_install:
  - docker build -t sarunaskas/react-test -f ./client/Dockerfile.dev ./client/

script:
  - docker run sarunaskas/react-test npm test -- --coverage

after_success:
  - docker build -t sarunaskas/multi-client ./client
  - docker build -t sarunaskas/multi-nginx ./nginx
  - docker build -t sarunaskas/multi-server ./server
  - docker build -t sarunaskas/multi-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # put them to docker hub
  - docker push sarunaskas/multi-client
  - docker push sarunaskas/multi-nginx
  - docker push sarunaskas/multi-server
  - docker push sarunaskas/multi-worker
